name: 'IOC CI/CD Pipeline'
description: 'Validate, enrich, and hunt for Indicators of Compromise'
author: 'Security Team'

inputs:
  command:
    description: 'Command to run: validate, inventory, or publish'
    required: true
  ioc_file:
    description: 'Path to the IOC input file (required for validate/inventory, not used for publish)'
    required: false
    default: ''
  confidence_threshold:
    description: 'Minimum confidence score (0-100) for IOCs to pass validation (validate only)'
    required: false
    default: '70'
  override_threshold:
    description: 'Set to true to allow below-threshold IOCs (validate only)'
    required: false
    default: 'false'
  enrichment_sources:
    description: 'Comma-separated enrichment sources to use (virustotal,abuseipdb,otx)'
    required: false
    default: 'virustotal,abuseipdb,otx'
  publishers:
    description: 'Comma-separated hunting publishers to use (splunk,elastic)'
    required: false
    default: 'splunk,elastic'
  max_ioc_age_days:
    description: 'Maximum IOC age in days for hunting (publish command only)'
    required: false
    default: '30'
  master_csv:
    description: 'Path to master IOC inventory CSV file'
    required: false
    default: 'iocs/master-indicators.csv'

outputs:
  has_malformed:
    description: 'Whether malformed IOCs were detected'
  has_below_threshold:
    description: 'Whether any IOCs scored below the confidence threshold'
  report_path:
    description: 'Path to the enrichment report Markdown file'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.ioc_file }}
    - --threshold=${{ inputs.confidence_threshold }}
    - --override=${{ inputs.override_threshold }}
    - --master-csv=${{ inputs.master_csv }}
  env:
    ENRICHMENT_SOURCES: ${{ inputs.enrichment_sources }}
    PUBLISHERS: ${{ inputs.publishers }}
    MAX_IOC_AGE_DAYS: ${{ inputs.max_ioc_age_days }}

branding:
  icon: 'shield'
  color: 'blue'
